apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnative
spec:
  selector:
    matchLabels:
      app: cloudnative
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudnative
    spec:
      serviceAccount: cloudnative
      containers:
        - name: cloudnative
          image: mnibm/cloud-native-container:2
          securityContext:
            privileged: true
